search_recordings:
  fields:
    device_id:
      example: DS-7608NI-K2-8P0000000000AAAA000000000AAAA
      selector:
        text:
    channel:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 64
          mode: box
    start_time:
      selector:
        datetime:
    end_time:
      selector:
        datetime:
    event_type:
      example: motion
      selector:
        select:
          custom_value: true
          options:
            - motion
            - timing
            - alarm
    limit:
      default: 100
      selector:
        number:
          min: 1
          max: 1000
          mode: box

export_recording:
  fields:
    device_id:
      selector:
        text:
    channel:
      required: true
      selector:
        number:
          min: 1
          max: 64
          mode: box
    start_time:
      required: true
      selector:
        datetime:
    end_time:
      required: true
      selector:
        datetime:
    filename:
      example: front_door_break_in.mp4
      selector:
        text:

ptz:
  fields:
    device_id:
      selector:
        text:
    channel:
      required: true
      selector:
        number:
          min: 1
          max: 64
          mode: box
    pan:
      default: 0
      selector:
        number:
          min: -100
          max: 100
    tilt:
      default: 0
      selector:
        number:
          min: -100
          max: 100
    zoom:
      default: 0
      selector:
        number:
          min: -100
          max: 100
    preset:
      selector:
        number:
          min: 1
          max: 255
          mode: box
    duration:
      default: 0.5
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: s

reboot:
  fields:
    device_id:
      selector:
        text:

enable_notifications:
  fields:
    device_id:
      selector:
        text:
    event_type:
      example: VMD
      selector:
        select:
          multiple: true
          custom_value: true
          options:
            - VMD
            - linedetection
            - fielddetection
            - tamperdetection
            - facedetection
    channel:
      example: "[1, 2]"
      selector:
        text:
          multiple: true
